
project_id = "mpvxppgoyadwukkfoccs"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
file_size_limit = "50MiB"
image_transformation = {enabled = true}

[auth]
enabled = true
port = 54328
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = false
enable_sms_confirmations = false
enable_phone_signup = false
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_manual_linking = false

[edge-runtime]
enabled = true
port = 54329

[functions.ftp-list]
verify_jwt = false

[functions.ftp-upload]
verify_jwt = false

[functions.ftp-download]
verify_jwt = false

[functions.ftp-delete]
verify_jwt = false

[functions.bacula-proxy]
verify_jwt = true

[functions.send-whatsapp-message]
verify_jwt = true

[functions.send-bacula-daily-report]
verify_jwt = true

[functions.wazuh-proxy]
verify_jwt = true

[functions.unifi-website-proxy]
verify_jwt = false
